import swaggerAutogen from 'swagger-autogen'

const outputFile = './docs/swagger_output.json'
const endpointsFiles = ['src/routes/index.ts']

swaggerAutogen({ openapi: '3.0.0' })

const doc = {
  info: {
    version: '1.0.0',
    title: 'Jukebox API',
    description: 'Documentation automatically generated by the <b>swagger-autogen</b> module.'
  },
  host: 'localhost:' + process.env.PORT,
  basePath: '/',
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'Base',
      description: 'General endpoints'
    },
    {
      name: 'User',
      description: 'User management'
    },
    {
      name: 'Spotify',
      description: 'Communicate with Spotify'
    }
  ],
  components: {
    securitySchemes: {
      Bearer: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
        in: 'header'
      }
    }
  },
  security: [
    {
      Bearer: []
    }
  ],
  definitions: {}
}
export const initializeSwagger = async () => {
  await swaggerAutogen(outputFile, endpointsFiles, doc)
}
