# Development Image
################################################
FROM node:20-bookworm

WORKDIR /app

COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

ARG NODE_ENV=development

USER root

RUN npm install -g npm && \
    npm install -g typescript && \
    npm install -g rimraf && \
    npm install 

COPY ./tsconfig.json ./tsconfig.json
COPY ./jest.config.ts ./jest.config.ts
COPY ./server /app/server

RUN npm run build

EXPOSE 8000
VOLUME ["/app/server"]

CMD ["npm", "start"]
