# Taskfile docs: https://taskfile.dev/
version: '3'

tasks:
  #########################################
  # Server Commands
  #########################################
  # TODO: Add commands

  #########################################
  # Jukebox-Types Package
  #########################################

  publish-types:
    summary: 'Publish types package version to GitHub packages'
    desc: |
      Example usage: "task publish-types -- 1.0.0". Must login to NPM using "npm login", and
      must have write permissions for the package: https://www.npmjs.com/package/jukebox-types.
      This command writes a new version to the package.json.
    vars:
      V: '{{.CLI_ARGS}}'
    cmds:
      - npm version {{.V}} --workspace jukebox-types
      - npm publish --workspace jukebox-types --access public
      - npm install jukebox-types@{{.V}} --save-dev
