const swaggerAutogen = require('swagger-autogen')()

const outputFile = './swagger_output.json'
// const endpointsFiles = ['./controllers/main.controller.js', './controllers/spotify.controller.js']
const endpointsFiles = ['./routes/routes.js','./controllers/main.controller.js', './controllers/authentication.controller.js']

const doc = {
    info: {
        version: "2.0.0",
        title: "Jukebox API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3000",
    basePath: "/",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Base",
            "description": "General endpoints"
        },
        {
            "name": "Authentication",
            "description": "Used to login to Spotify"
        },
        {
            "name": "Spotify",
            "description": "Communicate with Spotify"
        }
    ],
    securityDefinitions: {
        api_key: {
            type: "apiKey",
            name: "auth_token",
            in: "header"
        },
    },
    definitions: {
        SpotifyAuthSuccess: {
            success: true,
            access_token: '[access_token]',
            refresh_token: '[refresh_token]',
            home: 'root'
        }
    }
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./server.js');
})
